apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-prod
  template:
    metadata:
      labels:
        app: app-prod
    spec:
      containers:
      - env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: app-prod-env
        image: fiser/base-docker-microservices:app-prod
        name: symfony-app-prod
        resources: {}
        volumeMounts:
        - mountPath: /app/App/var/logs
          name: app-prod-claim1
      restartPolicy: Always
      volumes:
      - name: app-prod-claim1
        persistentVolumeClaim:
          claimName: app-prod-claim1