apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: app-prod
    spec:
      containers:
      - env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: app-prod-env
        image: fiser/base-docker-microservices:composite-prod
        name: symfony-app-prod
        resources: {}
        volumeMounts:
        - mountPath: /app/App
          name: app-data
        - mountPath: /app/App/var/logs
          name: app-prod-claim1
      restartPolicy: Always
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data
      - name: app-prod-claim1
        persistentVolumeClaim:
          claimName: app-prod-claim1