apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: compositeui-prod
  name: compositeui-prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: compositeui-prod
    spec:
      containers:
      - env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: compositeui-prod-env
        image: fiser/base-docker-microservices:composite-prod
        name: compositeui-prod
        resources: {}
        volumeMounts:
        - mountPath: /app/CompositeUi
          name: compositeui-data
      restartPolicy: Always
      volumes:
      - name: compositeui-data
        persistentVolumeClaim:
          claimName: compositeui-data
status: {}
