apiVersion: v1
data:
  APP_ENV: HOWIFHBAVAFIOF672FNDKFGAJjJjeq2nN
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: compositeui-prod-env
  name: compositeui-prod-env
