apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-prod
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-prod
    spec:
      containers:
      - env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: db-prod-env
        image: mongo:4.1.3
        name: mongodb-prod
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-prod-claim0
      restartPolicy: Always
      volumes:
      - name: db-prod-claim0
        persistentVolumeClaim:
          claimName: db-prod-claim0
status: {}
