version: '3'

networks:
  crv_prod_network:
    driver: bridge

services:
  db-prod:
    container_name: mongodb-prod
    image: mongo:4.1.3
    restart: always
    env_file:
      - ../Docker/db/prod/.env
    volumes:
      - ../Docker/volumes/mongo/prod/database:/data/db
    networks:
      crv_prod_network:
        aliases:
          - mongo
    ports:
      - "27017:27017"

  app-prod:
    container_name: symfony-app-prod
    image: fiser/base-docker-microservices:composite-prod
    restart: always
    volumes:
      - app_data:/app/App:rw
      -  ../Docker/volumes/log/prod/App:/app/App/var/logs
    networks:
      crv_prod_network:
        aliases:
          - app
    env_file:
      - .env
    depends_on:
      - db-prod

  compositeui-prod:
    container_name: compositeui-prod
    image: fiser/base-docker-microservices:composite-prod
    volumes:
      - compositeui_data:/app/CompositeUi:rw
    networks:
      crv_prod_network:
        aliases:
          - composite-ui
    env_file:
      - .env

  nginx-prod:
    container_name: nginx-server-prod
    image: fiser/base-docker-microservices:nginx-prod
    restart: always
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - app_data:/app/App:rw
      - compositeui_data:/app/CompositeUi:rw
      - ../Docker/volumes/log/prod/Nginx:/var/log/nginx
    depends_on:
      - app-prod
    env_file:
      - .env
    networks:
      crv_prod_network:
        aliases:
          - nginx

volumes:
    app_data:
        driver: local
    compositeui_data:
        driver: local