version: '3.4'

networks:
  crv_dev_network:
    driver: bridge

services:
  mysql-dev:
    container_name: mysql-dev
    image: mysql:8.0.13
    env_file:
      - ../.env.dev
    volumes:
      - ../DockerComposer/volumes/mysql/dev/database:/var/lib/mysql
    networks:
      crv_dev_network:
        aliases:
          - mysql
    ports:
      - "3307:3306"
  app-dev:
    container_name: app-dev
    build:
      context: ../
      dockerfile: ./Docker/app/prod/Dockerfile
    restart: always
    volumes:
      -  ../:/app
      -  ../DockerComposer/logs/dev/App:/app/App/var/log
    networks:
      crv_dev_network:
        aliases:
          - app
    env_file:
      - ../.env.dev
    depends_on:
      - mysql-dev
  ecommerce-dev:
    container_name: ecommerce-dev
    build:
      context: ../
      dockerfile: ./Docker/nginx/prod/Dockerfile
      target: ecommerce
      args:
        env: dev
    restart: always
    command: ["php-fpm", "-F"]
    volumes:
      -  ../:/app
      -  ../DockerComposer/logs/dev/ECommerce:/app/ECommerce/var/log
    networks:
      crv_dev_network:
        aliases:
          - ecommerce
    env_file:
      - ../.env.dev
    depends_on:
      - mysql-dev
  nginx-dev:
    container_name: nginx-server-dev
    build:
      context: ../
      dockerfile: ./Docker/nginx/prod/Dockerfile
      target: nginx
      args:
        env: dev
    restart: always
    ports:
      - "8080:80"
    volumes:
      -  ../:/app
      - ../DockerComposer/logs/dev/Nginx:/var/log/nginx
    depends_on:
      - app-dev
    env_file:
      - ../.env.dev
    networks:
      crv_dev_network:
        aliases:
          - nginx