version: '3.3'

networks:
  crv_prod_network:
    driver: bridge

services:
  mysql-prod:
    container_name: mysql-prod
    image: mysql:8.0.13
    env_file:
    - ../Docker/mysql/prod/.env
    volumes:
    - ../DockerComposer/volumes/mysql/prod/database:/var/lib/mysql
    networks:
      crv_prod_network:
        aliases:
        - mysql
    ports:
    - "3306:3306"
  ecommerce-prod:
    container_name: ecommerce-prod
    build:
      context: ../
      dockerfile: ./Docker/ecommerce/prod/Dockerfile
    restart: always
    volumes:
    -  ../DockerComposer/logs/prod/ECommerce:/app/ECommerce/var/logs
    networks:
      crv_prod_network:
        aliases:
        - ecommerce
    env_file:
    - ../Docker/ecommerce/prod/.env
    depends_on:
    - mysql-prod
  app-prod:
    container_name: app-prod
    build:
      context: ../
      dockerfile: ./Docker/app/prod/Dockerfile
    restart: always
    volumes:
      -  ../DockerComposer/logs/prod/App:/app/App/var/logs
    networks:
      crv_prod_network:
        aliases:
          - app
    env_file:
      - ../Docker/app/prod/.env
  nginx-prod:
    container_name: nginx-server-prod
    build:
      context: ../
      dockerfile: ./Docker/nginx/prod/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../DockerComposer/logs/prod/Nginx:/var/log/nginx
    depends_on:
      - app-prod
      - ecommerce-prod
    env_file:
      - ../Docker/nginx/prod/.env
    networks:
      crv_prod_network:
        aliases:
          - nginx