version: '3.3'

networks:
  crv_dev_network:
    driver: bridge

services:
  mysql-dev:
    container_name: mysql-dev
    image: mysql:8.0.13
    env_file:
    - ../Docker/mysql/dev/.env
    volumes:
      - ../DockerComposer/volumes/mysql/dev/database:/var/lib/mysql
      - ../DockerComposer/logs/dev/mysql:/var/log/Mysql
    networks:
      crv_dev_network:
        aliases:
        - mysql
    ports:
    - "3307:3306"

  php:
    container_name: php
    build:
      context: ../
      dockerfile: ./Docker/app/dev/Dockerfile
    volumes:
      - ../:/app
    networks:
      crv_dev_network:
        aliases:
          - php
    env_file:
    - ../Docker/app/dev/.env
    depends_on:
    - mysql-dev
  ecommerce-dev:
    container_name: ecommerce-dev
    build:
      context: ../
      dockerfile: ./Docker/ecommerce/prod/Dockerfile
    restart: always
    volumes:
      -  ../:/app
      -  ../DockerComposer/logs/dev/ECommerce:/app/ECommerce/var/logs
    networks:
      crv_dev_network:
        aliases:
          - ecommerce
    env_file:
      - ../Docker/ecommerce/prod/.env
    depends_on:
      - mysql-dev
  nginx-dev:
    container_name: nginx-server-dev
    build:
      context: ../
      dockerfile: ./Docker/nginx/dev/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../.:/app
      - ../DockerComposer/logs/dev/Nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      crv_dev_network:
        aliases:
          - nginx
    env_file:
    - ../Docker/nginx/dev/.env